type: repo
title: donnemartin/system-design-primer
url: https://github.com/donnemartin/system-design-primer
language: en
date_consumed: 2026-04-29
date_added: 2026-04-29
status: processed
tags: []
related_concepts: []
